[package]
name = "rust_btc_passphrase_finder"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
bitcoin = "0.26"
bip39 = "2.0"
indicatif = "0.16"
rayon = "1.5"
memmap = "0.7"
log = "0.4"
simplelog = "0.11"