# Konfigurationsdatei für das Bitcoin Passphrase Brute-Force Tool

# 1. BIP39 Mnemonic (Seed-Phrase/test-> frog estate inquiry erupt replace hole trumpet obvious else fiction throw raccoon)
seed_phrase = "update decline dentist awake ring sunset appear melt visa fancy quote paddle"

# 2. Zieladresse (die das Tool finden soll/test-> 15Dq8GudXF25CdfKFLkSjD7i376WgV4KHH)
expected_address = "bc1qwy52fm567ws20h9msv96rmln2gcatjcs9f5f4txmwmfrm6alz0kszy90lc"

# 3. Pfad zur Wortliste (für den test ind der Wortlist -> bitcoin123)
wordlist_path = "wordlists/wordlist.txt"

# 4. Anzahl der Threads für parallele Verarbeitung
num_threads = 8