################################################################################
# Bitcoin Passphrase Finder - Konfiguration
################################################################################

#------------------------------------------------------------------------------
# WESENTLICHE PARAMETER
#------------------------------------------------------------------------------
# Seed-Phrase zur Generierung der Passphrase
seed_phrase = "census claim gravity daughter deliver abuse banner join own neither exist ahead"

# Erwartete Bitcoin-Adresse, die zur generierten Passphrase passen sollte
expected_address = "bc1prwx9drhn3wxwwq27ctyuelkyks79s8w6n9a4cye4l5gsltwrx8fqrkgnkd"

# Anzahl der zu durchsuchenden Adresspfade (1, 2 oder 3)
address_paths_to_search = 1

#------------------------------------------------------------------------------
# PASSPHRASEN-GENERIERUNG
#------------------------------------------------------------------------------
# Regex-Muster für die Passphrasen-Generierung (siehe docs/REGEX_PATTERNS.md für Details)
# gesucht passphrase -> zEZqxuEiLs3C1KsG
passphrase = "bijNYE5[A-Z][a-z]Lt1Ck2[A-Z]"

# Pfad zur Datei, in der die generierten Passphrasen gespeichert werden
wordlist_path = "wordlists/wordlist.txt"

# Anzahl der für die Generierung zu verwendenden Threads
num_threads = 4