# Configuration file for the Bitcoin Passphrase Brute-Force Tool

# Seed phrase used for generating the passphrase
seed_phrase = "model sign help plug liar chapter ethics gold use deny liquid exit"

# Expected Bitcoin address that should match the generated passphrase
expected_address = "bc1p0zgfnea4yp8snmy4jx20jleemlldkm8xwxuyz3tp9tdd9vm6ym5qyhpt8q"

# Path to the file where the generated passphrases will be saved
wordlist_path = "wordlists/wordlist.txt"

# Number of threads to be used for generation
num_threads = 4

# Template for the passphrase with placeholders
passphrase = "'spe2''low1'"

# Characters to be used for the placeholders
upp1 = "ABC"  # Uppercase letters ABCDEFGHIJKLMNOPQRSTUVWXYZ
upp2 = "DEF"  # Uppercase letters ABCDEFGHIJKLMNOPQRSTUVWXYZ
low1 = "abc"  # Lowercase letters abcdefghijklmnopqrstuvwxyz
low2 = "abc"  # Lowercase letters abcdefghijklmnopqrstuvwxyz
dig1 = "789"  # Digits 0123456789
dig2 = "789"  # Digits 0123456789
spe1 = "!§$"  # Special characters +*#'<>^°!§$%&=?
spe2 = "!§$"  # Special characters +*#'<>^°!§$%&=?

# Number of address paths to search (1, 2, or 3)
address_paths_to_search = 3