# Configuration file for the Bitcoin Passphrase Brute-Force Tool

# Seed phrase used for generating the passphrase
seed_phrase = "where buddy physical crawl orphan cricket rain mandate write auto garment celery"

# Expected Bitcoin address that should match the generated passphrase
expected_address = "bc1ptfmjpnx0x83rtner7844szeyxt5ed63fxx6par28y8snqsugucps8dc3ul"

# Path to the file where the generated passphrases will be saved
wordlist_path = "wordlists/wordlist.txt"

# Number of threads to be used for generation
num_threads = 4

# Template for the passphrase with placeholders
passphrase = "Satoshi'uppercase'1'lowercase''digits'2'special'"

# Characters to be used for the 'uppercase' placeholder
uppercase = "ABCD"  # Uppercase letters ABCDEFGHIJKLMNOPQRSTUVWXYZ

# Characters to be used for the 'lowercase' placeholder
lowercase = "xyz"  # Lowercase letters abcdefghijklmnopqrstuvwxyz

# Characters to be used for the 'digits' placeholder
digits = "789"  # Digits 0123456789

# Characters to be used for the 'special' placeholder
special = "!§$%&=?"  # Special characters +*#'<>^°!§$%&=?

# Number of address paths to search (1, 2, or 3)
address_paths_to_search = 3